### ISSUE TITLE
Event ID Query String & Database Mis-match

### ISSUE THREAD

**Issue by ben-wals** [The-Iceburg/blgc#10]
The Article Identifier on the database and the query string don't match and they should.

Example:

<img width="597" alt="image" src="https://github.com/The-Iceburg/blgc/assets/67003539/c0989609-1e86-4d39-8d0f-d113ff19769b">

Database article identifier = 1

<img width="269" alt="image" src="https://github.com/The-Iceburg/blgc/assets/67003539/83816b78-75f4-4639-a4f7-5c8bfda89a2b">

Website Query String Link ID = 0 

I'm presuming this may be a discrepancy between the localhost database and the actual database or on oversight when it was originally programmed. Either way this needs fixing as work is hopefully starting on my end for the dynamic article viewer soon.

**Comment by Dockuin** [comment]
It should be a fairly simple fix in the javascript

However, I would like to point out how this is mainly due to 2 different numbering systems in the database and website itself.
In the database, the first item is of item 1 but in the html, the first div is "article-about-us-0" (starting from 0).
Realistically speaking, this issue is formed from the lack of parity between backend and frontend

**Comment by ben-wals** [comment]
Agreed, however when #9 is implemented this won't matter anyway as the article ID links with have no correlation with the div class names.
